alias: Zendure Akku Automatik (V9 KI + PID Pro)
description: >
  KI-gesteuerte Ladeplanung mit stabiler PI-Entladeregelung, Null-Einspeisung,
  SoC-Schutz und Peak-Vorhersage.

trigger:
  - platform: state
    entity_id:
      - sensor.zendure_akku_steuerungsempfehlung
      - sensor.gesamtverbrauch
      - sensor.bezug
      - sensor.einspeisung
      - sensor.sb2_5_1vl_40_401_pv_power
  - platform: time_pattern
    seconds: /10

action:
  - variables:
      soc: "{{ states('sensor.solarflow_2400_ac_electric_level')|float(0) }}"
      soc_min: "{{ states('input_number.zendure_soc_reserve_min')|float(12) }}"
      soc_max: "{{ states('input_number.zendure_soc_ziel_max')|float(95) }}"
      soc_notfall: >
        {% set min_soc = states('input_number.zendure_soc_reserve_min')|float(12) %}
        {{ [min_soc - 4, 5] | max }}
      notfall_power: "{{ states('input_number.zendure_notladeleistung')|float(300) }}"
      pv: "{{ states('sensor.sb2_5_1vl_40_401_pv_power')|float(0) }}"
      haus: "{{ states('sensor.gesamtverbrauch')|float(0) }}"
      einspeisung: "{{ states('sensor.einspeisung')|float(0) }}"
      preis: "{{ states('sensor.electricity_price_paul_schneider_strasse_39')|float(0) }}"
      recommendation: "{{ states('sensor.zendure_akku_steuerungsempfehlung') }}"
      max_discharge: "{{ states('input_number.zendure_max_entladeleistung')|float(700) }}"
      kp: 0.6
      ki: 0.02
      pid_i_prev: "{{ states('input_number.zendure_pid_i_term')|float(0) }}"

  - choose:
      - conditions:
          - condition: template
            value_template: "{{ soc <= soc_notfall }}"
        sequence:
          - service: select.select_option
            target:
              entity_id: select.solarflow_2400_ac_ac_mode
            data:
              option: input
          - service: number.set_value
            target:
              entity_id: number.solarflow_2400_ac_input_limit
            data:
              value: "{{ notfall_power }}"
          - stop

  - choose:
      - conditions:
          - condition: template
            value_template: "{{ recommendation in ['entladen','preis_entladen'] }}"
        sequence:
          - service: select.select_option
            target:
              entity_id: select.solarflow_2400_ac_ac_mode
            data:
              option: output
          - variables:
              real_load: "{{ [haus - pv, 0] | max }}"
              current_output: "{{ states('number.solarflow_2400_ac_output_limit')|float(0) }}"
              error: "{{ real_load - current_output }}"
              p_term: "{{ error * kp }}"
              i_term: "{{ pid_i_prev + error * ki }}"
              new_output: "{{ [current_output + p_term + i_term, max_discharge] | min }}"
          - service: number.set_value
            target:
              entity_id: number.solarflow_2400_ac_output_limit
            data:
              value: "{{ new_output|round(0) }}"
          - service: number.set_value
            target:
              entity_id: input_number.zendure_pid_i_term
            data:
              value: "{{ i_term|round(2) }}"
mode: single
