alias: Zendure Akku Automatik (V10 KI + PID Pro)
description: >
  KI-gesteuerte Ladeplanung mit stabiler PI-Entladeregelung (PID-Light),
  Null-Einspeisung, SoC-Schutz (Reserve/Notfall) und Peak-Vorhersage.
triggers:
  - trigger: state
    entity_id:
      - sensor.zendure_akku_steuerungsempfehlung
      - sensor.gesamtverbrauch
      - sensor.bezug
      - sensor.einspeisung
      - sensor.sb2_5_1vl_40_401_pv_power
  - trigger: time_pattern
    seconds: /10
conditions: []
actions:
  - variables:
      soc: "{{ states('sensor.solarflow_2400_ac_electric_level')|float(0) }}"
      soc_min: "{{ states('input_number.zendure_soc_reserve_min')|float(12) }}"
      soc_max: "{{ states('input_number.zendure_soc_ziel_max')|float(95) }}"
      soc_notfall: >
        {% set min_soc =
        states('input_number.zendure_soc_reserve_min')|float(12) %} {{ [min_soc
        - 4, 5] | max }}
      notfall_power: "{{ states('input_number.zendure_notladeleistung')|float(300) }}"
      pv: "{{ states('sensor.sb2_5_1vl_40_401_pv_power')|float(0) }}"
      haus: "{{ states('sensor.gesamtverbrauch')|float(0) }}"
      einspeisung: "{{ states('sensor.einspeisung')|float(0) }}"
      bezug: "{{ states('sensor.bezug')|float(0) }}"
      preis: >-
        {{ states('sensor.electricity_price_paul_schneider_strasse_39')|float(0)
        }}
      mode_user: "{{ states('input_select.zendure_betriebsmodus') }}"
      recommendation: "{{ states('sensor.zendure_akku_steuerungsempfehlung') }}"
      max_charge: "{{ states('input_number.zendure_max_ladeleistung')|float(2000) }}"
      max_discharge: "{{ states('input_number.zendure_max_entladeleistung')|float(700) }}"
      abs_tol: 10
      kp: 0.6
      ki: 0.02
      pid_i_prev: "{{ states('input_number.zendure_pid_i_term')|float(0) }}"
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ mode_user == 'Manuell' }}"
        sequence:
          - stop: Manueller Modus aktiv – keine Automation aktiv.
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ soc <= soc_notfall }}"
        sequence:
          - action: select.select_option
            target:
              entity_id: select.solarflow_2400_ac_ac_mode
            data:
              option: input
          - action: number.set_value
            target:
              entity_id: number.solarflow_2400_ac_input_limit
            data:
              value: "{{ notfall_power }}"
          - stop: Notladung aktiv – keine Entladung erlaubt.
  - choose:
      - conditions:
          - condition: template
            value_template: >
              {{ recommendation in ['laden','billig_laden','ki_laden'] and soc <
              soc_max }}
        sequence:
          - action: select.select_option
            target:
              entity_id: select.solarflow_2400_ac_ac_mode
            data:
              option: input
          - variables:
              surplus: "{{ [pv - haus - 50, 0] | max }}"
              ladeleistung: |
                {% if recommendation in ['billig_laden', 'ki_laden'] %}
                  {{ max_charge }}
                {% else %}
                  {{ [surplus, max_charge] | min }}
                {% endif %}
          - action: number.set_value
            target:
              entity_id: number.solarflow_2400_ac_input_limit
            data:
              value: "{{ ladeleistung|round(0) }}"
          - action: number.set_value
            target:
              entity_id: number.solarflow_2400_ac_output_limit
            data:
              value: 0
  - choose:
      - conditions:
          - condition: template
            value_template: >
              {{ recommendation in ['entladen','preis_entladen'] and soc >
              soc_min }}
        sequence:
          - action: select.select_option
            target:
              entity_id: select.solarflow_2400_ac_ac_mode
            data:
              option: output
          - variables:
              real_load: "{{ [haus - pv, 0] | max }}"
              current_output: "{{ states('number.solarflow_2400_ac_output_limit')|float(0) }}"
              error: "{{ real_load - current_output }}"
              p_term: "{{ error * kp }}"
              i_unclamped: "{{ pid_i_prev + error * ki }}"
              i_term: "{{ [ [i_unclamped, 0] | max, max_discharge ] | min }}"
              output_raw: "{{ current_output + p_term + i_term }}"
              output_clamped: "{{ [ [output_raw, 0] | max, max_discharge ] | min }}"
              new_output: |
                {% if einspeisung > 30 %}
                  {# Sofortiger Eingriff bei Einspeisung: Netz in Richtung 0 ziehen #}
                  {{ [real_load, max_discharge] | min }}
                {% elif error | abs < abs_tol %}
                  {# Totzone: kleine Abweichung → nichts tun #}
                  {{ current_output }}
                {% else %}
                  {{ output_clamped }}
                {% endif %}
              i_next: |
                {% if error | abs < abs_tol %}
                  {# In der Totzone I-Term langsam abbauen, um Überschwingen zu vermeiden #}
                  {{ pid_i_prev * 0.9 }}
                {% else %}
                  {{ i_term }}
                {% endif %}
          - action: number.set_value
            target:
              entity_id: number.solarflow_2400_ac_output_limit
            data:
              value: "{{ new_output|round(0) }}"
          - action: number.set_value
            target:
              entity_id: number.solarflow_2400_ac_input_limit
            data:
              value: 0
          - action: number.set_value
            target:
              entity_id: input_number.zendure_pid_i_term
            data:
              value: "{{ i_next|round(2) }}"
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ recommendation == 'standby' }}"
        sequence:
          - action: number.set_value
            target:
              entity_id:
                - number.solarflow_2400_ac_input_limit
                - number.solarflow_2400_ac_output_limit
            data:
              value: 0
mode: single
